name: nix

on: [push, pull_request]

jobs:
  nix:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: s2p
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: env NIXPKGS_ALLOW_UNFREE=1 nix build --impure -L .#dockerImage
      - uses: docker/login-action@v3
        with:
          registry: git.ipol.im
          username: s2p
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: |
          ./result | docker load
          docker tag s2p-hd-cuda:latest git.ipol.im/s2p/s2p-hd-cuda:$GITHUB_SHA
          docker push git.ipol.im/s2p/s2p-hd-cuda:$GITHUB_SHA
