name: tests

on: [push, pull_request]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install libgdal-dev gdal-bin libfftw3-dev libgeographic-dev
      - uses: actions/checkout@v2
        with:
            submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install s2p
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"
      - name: Run tests
        run: |
          pyproj sync -v --file us_nga_egm96_15
          pytest tests
